// <auto-generated />
using System;
using Anchor.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Anchor.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Anchor.Infrastructure.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("AccountConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsBootstrapAccount")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Anchor.Infrastructure.Data.Menu.MenuItemEntity", b =>
                {
                    b.Property<Guid>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSeasonal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisibleToGuests")
                        .HasColumnType("bit");

                    b.Property<Guid>("MenuSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly?>("OfferEndsOn")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("OfferStartsOn")
                        .HasColumnType("date");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("MenuItemId");

                    b.HasIndex("MenuSectionId");

                    b.ToTable("MenuItems", (string)null);

                    b.HasData(
                        new
                        {
                            MenuItemId = new Guid("c88652a0-c9f2-4a7d-b4ac-8ddbfc9ff4e5"),
                            Description = "Crisp white cheddar curds with your choice of dipping sauce.",
                            ImagePath = "images/menu/appetizers.svg",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("d67bd219-6d64-4a08-8ce4-d036a0c7b16d"),
                            Name = "Cheese Curds",
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemId = new Guid("5c3a9530-0f24-4d62-883b-f01b0a4286c2"),
                            Description = "Served with salsa and sour cream.",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("d67bd219-6d64-4a08-8ce4-d036a0c7b16d"),
                            Name = "Mini Tacos",
                            OfferStartsOn = new DateOnly(2026, 5, 31),
                            SortOrder = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("ff4ee65c-89e7-49f7-9023-8579ccb8307b"),
                            Description = "Loaded with cheese and served with salsa and sour cream.",
                            IsArchived = false,
                            IsSeasonal = true,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("d67bd219-6d64-4a08-8ce4-d036a0c7b16d"),
                            Name = "Quesadillas",
                            OfferEndsOn = new DateOnly(2026, 7, 10),
                            OfferStartsOn = new DateOnly(2026, 5, 9),
                            SortOrder = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("e75d8a92-f1d2-4d58-9cd0-9b7e80ce9d80"),
                            Description = "Finished with Boom Boom sauce for a bold bar-food favorite.",
                            ImagePath = "images/menu/appetizers.svg",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("d67bd219-6d64-4a08-8ce4-d036a0c7b16d"),
                            Name = "Fish Tacos",
                            OfferEndsOn = new DateOnly(2026, 6, 3),
                            OfferStartsOn = new DateOnly(2026, 5, 12),
                            SortOrder = 4
                        },
                        new
                        {
                            MenuItemId = new Guid("79663ef8-29ff-4d24-8b1c-cfa8dad8ba72"),
                            Description = "Choice of one sauce.",
                            ImagePath = "images/menu/wings.svg",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("4a3a2d15-2af0-44a7-84c8-67b603a3ddb4"),
                            Name = "Traditional or Boneless (6)",
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemId = new Guid("1c4d4f34-5260-4f7d-abcb-1c6875b7ebf8"),
                            Description = "Choice of two sauces.",
                            ImagePath = "images/menu/wings.svg",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("4a3a2d15-2af0-44a7-84c8-67b603a3ddb4"),
                            Name = "Traditional or Boneless (12)",
                            SortOrder = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("ca5cd1b7-8c73-4b21-b3e4-8e98fea44ee9"),
                            Description = "Upgrade any wing order with a side of fries.",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("4a3a2d15-2af0-44a7-84c8-67b603a3ddb4"),
                            Name = "Add Fries",
                            SortOrder = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("73ea7283-893f-4d14-8081-39f63bd54d13"),
                            Description = "Crisp greens, tomatoes, peppers, shaved red onions, and your choice of dressing.",
                            ImagePath = "images/menu/salads.svg",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("31e9cb99-5fca-4a4a-a04b-89b97c926a52"),
                            Name = "The Anchor Salad",
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemId = new Guid("8c5bde4d-3fb2-4a02-8ab5-40d3e0b49387"),
                            Description = "Finished with crumbled smoked salmon and poppyseed dressing.",
                            ImagePath = "images/menu/salads.svg",
                            IsArchived = false,
                            IsSeasonal = true,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("31e9cb99-5fca-4a4a-a04b-89b97c926a52"),
                            Name = "Smoked Salmon Salad",
                            OfferEndsOn = new DateOnly(2026, 7, 10),
                            OfferStartsOn = new DateOnly(2026, 5, 26),
                            SortOrder = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("e9d5a6c9-9a4c-4e98-8c72-2ae28bfcba97"),
                            Description = "Bacon, tomatoes, greens, and your choice of dressing.",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("31e9cb99-5fca-4a4a-a04b-89b97c926a52"),
                            Name = "BLT Salad",
                            SortOrder = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("db2a7b2f-d9e9-4433-80a3-baeb5e5b5728"),
                            Description = "Cup or bowl, updated as the kitchen rotates specials.",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("31e9cb99-5fca-4a4a-a04b-89b97c926a52"),
                            Name = "Seasonal Soup",
                            SortOrder = 4
                        },
                        new
                        {
                            MenuItemId = new Guid("590cc0e4-8be8-48e8-97b8-908ea7a1fc9a"),
                            Description = "Lettuce, tomato, and mayo on a toasted bun.",
                            ImagePath = "images/menu/sandwiches.svg",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("7f644c28-9275-4df8-8e4b-482f47568cfb"),
                            Name = "Grilled Chicken Sandwich",
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemId = new Guid("3b7745b6-66d4-4db7-8ee3-b018834f58f7"),
                            Description = "Grilled sirloin, smoked gouda, peppers, and onions.",
                            ImagePath = "images/menu/sandwiches.svg",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("7f644c28-9275-4df8-8e4b-482f47568cfb"),
                            Name = "Steak Sandwich",
                            SortOrder = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("1af4708e-e741-4621-95e3-6c8f24af2be6"),
                            Description = "Swiss cheese, grilled ham, smoked bacon, and classic ranch.",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("7f644c28-9275-4df8-8e4b-482f47568cfb"),
                            Name = "Ranch Melt",
                            SortOrder = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("e1fd2b7f-d7e0-47cc-9e3e-4bc3a30aa4b8"),
                            Description = "Breaded walleye on a toasted bun.",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("7f644c28-9275-4df8-8e4b-482f47568cfb"),
                            Name = "Walleye Sandwich",
                            SortOrder = 4
                        },
                        new
                        {
                            MenuItemId = new Guid("7626d0df-9f8a-4fe8-9062-3596165e148a"),
                            Description = "Fresh hand-pattied burger; add cheese if desired.",
                            ImagePath = "images/menu/burgers.svg",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("198ccf8a-72fd-4278-a360-f36d5871e58b"),
                            Name = "Classic Hamburger",
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemId = new Guid("ecfc8bfa-6c51-4607-b7ff-fe9f59db8fbc"),
                            Description = "A familiar favorite with bacon and melty cheese.",
                            ImagePath = "images/menu/burgers.svg",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("198ccf8a-72fd-4278-a360-f36d5871e58b"),
                            Name = "Bacon Cheeseburger",
                            SortOrder = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("6e97a8ee-16b1-4feb-b6e0-2ab4e56658a0"),
                            Description = "Bacon, BBQ sauce, and a crisp onion ring.",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("198ccf8a-72fd-4278-a360-f36d5871e58b"),
                            Name = "Western Burger",
                            SortOrder = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("90dce7e3-9cc6-4732-b7d2-f4d43056fbb8"),
                            Description = "Bacon, American cheese, and egg.",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("198ccf8a-72fd-4278-a360-f36d5871e58b"),
                            Name = "Sunrise Burger",
                            SortOrder = 4
                        },
                        new
                        {
                            MenuItemId = new Guid("0d440a2b-06a3-47f9-b129-1544f2f391a8"),
                            Description = "Grilled or crispy chicken, tomatoes, onions, lettuce, and dressing.",
                            ImagePath = "images/menu/wraps.svg",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("fa5da0f9-7e81-4b9d-9e11-fa5b1f828c72"),
                            Name = "Chicken Wrap",
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemId = new Guid("95f39c20-e1ba-4fd2-992d-8d9e19600d64"),
                            Description = "Steak, peppers, onions, cheese, lettuce, and dressing.",
                            ImagePath = "images/menu/wraps.svg",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("fa5da0f9-7e81-4b9d-9e11-fa5b1f828c72"),
                            Name = "Steak Wrap",
                            SortOrder = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("6f2a75a4-c1e2-458f-bde4-d825f987cc3d"),
                            Description = "Crispy chicken tossed in buffalo with ranch-style cooling balance.",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("fa5da0f9-7e81-4b9d-9e11-fa5b1f828c72"),
                            Name = "Buffalo Chicken Wrap",
                            SortOrder = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("b7ab3351-1b6b-45d0-b7b4-9782d79cfc65"),
                            Description = "Served with one side and a kid drink option.",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("2ea5e671-e8ac-4c8a-b3d9-4c136a32a71b"),
                            Name = "Mac & Cheese",
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemId = new Guid("5b1c6127-f7f0-497a-88b9-537e9110176f"),
                            Description = "The classic choice for a quick family meal.",
                            ImagePath = "images/menu/kids.svg",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("2ea5e671-e8ac-4c8a-b3d9-4c136a32a71b"),
                            Name = "Mini Corn Dogs",
                            SortOrder = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("06f858a2-f226-4b2f-a912-a6330bbf4ec1"),
                            Description = "Served with sauce.",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("2ea5e671-e8ac-4c8a-b3d9-4c136a32a71b"),
                            Name = "Chicken Strips",
                            SortOrder = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("8fcaa555-d618-4ad8-ae73-abf51854a329"),
                            Description = "Served warm with ice cream.",
                            ImagePath = "images/menu/desserts.svg",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("a8f0b603-e02d-49f5-873d-1bb6bfc16c0f"),
                            Name = "Chocolate Lava Cake",
                            OfferEndsOn = new DateOnly(2026, 6, 2),
                            OfferStartsOn = new DateOnly(2026, 5, 15),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemId = new Guid("44472c07-5f31-482a-8506-8a3c11cf1f26"),
                            Description = "Fair-style donuts for a casual sweet finish.",
                            ImagePath = "images/menu/desserts.svg",
                            IsArchived = false,
                            IsSeasonal = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("a8f0b603-e02d-49f5-873d-1bb6bfc16c0f"),
                            Name = "Mini Donuts",
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("Anchor.Infrastructure.Data.Menu.MenuItemPriceVariantEntity", b =>
                {
                    b.Property<Guid>("MenuItemPriceVariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("MenuItemPriceVariantId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("MenuItemPriceVariants", (string)null);

                    b.HasData(
                        new
                        {
                            MenuItemPriceVariantId = new Guid("916e3d70-2cb3-4273-a283-3241fb7fa0d0"),
                            Amount = 9m,
                            Label = "Regular",
                            MenuItemId = new Guid("c88652a0-c9f2-4a7d-b4ac-8ddbfc9ff4e5"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("2d12eaf9-ebca-4ea9-9ecc-663ff531d9ed"),
                            Amount = 9m,
                            Label = "Regular",
                            MenuItemId = new Guid("5c3a9530-0f24-4d62-883b-f01b0a4286c2"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("65e43e63-0a48-4b0c-b3b1-3956101a4f56"),
                            Amount = 11m,
                            Label = "Regular",
                            MenuItemId = new Guid("ff4ee65c-89e7-49f7-9023-8579ccb8307b"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("90ccf394-072e-47f2-80b5-85a00e58b6d5"),
                            Amount = 10m,
                            Label = "Regular",
                            MenuItemId = new Guid("e75d8a92-f1d2-4d58-9cd0-9b7e80ce9d80"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("5fa1bba0-2afa-45ef-be7b-6cc2c1354b9b"),
                            Amount = 9m,
                            Label = "Regular",
                            MenuItemId = new Guid("79663ef8-29ff-4d24-8b1c-cfa8dad8ba72"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("305be09a-e819-48de-b6bb-7771aabfd65a"),
                            Amount = 16m,
                            Label = "Regular",
                            MenuItemId = new Guid("1c4d4f34-5260-4f7d-abcb-1c6875b7ebf8"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("8e59cf80-d0fc-43a2-9442-9262f77d9b8a"),
                            Amount = 3m,
                            Label = "Regular",
                            MenuItemId = new Guid("ca5cd1b7-8c73-4b21-b3e4-8e98fea44ee9"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("388c7811-3724-4937-86f7-4e5de1836535"),
                            Amount = 10m,
                            Label = "Regular",
                            MenuItemId = new Guid("73ea7283-893f-4d14-8081-39f63bd54d13"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("d37f81b0-fb88-4daf-9fb8-dbd62afa8392"),
                            Amount = 13m,
                            Label = "Regular",
                            MenuItemId = new Guid("8c5bde4d-3fb2-4a02-8ab5-40d3e0b49387"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("957a3058-ad38-4da8-ae9a-d2670e408831"),
                            Amount = 12m,
                            Label = "Regular",
                            MenuItemId = new Guid("e9d5a6c9-9a4c-4e98-8c72-2ae28bfcba97"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("4db158e0-ee22-4b83-846a-f62446fd7fe5"),
                            Amount = 4m,
                            Label = "Cup",
                            MenuItemId = new Guid("db2a7b2f-d9e9-4433-80a3-baeb5e5b5728"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("7b70feb6-0dba-4aa0-8b6e-1a791b196d31"),
                            Amount = 6m,
                            Label = "Bowl",
                            MenuItemId = new Guid("db2a7b2f-d9e9-4433-80a3-baeb5e5b5728"),
                            SortOrder = 2
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("3f6a665b-3334-4315-b208-57cf9cc4b234"),
                            Amount = 13m,
                            Label = "Regular",
                            MenuItemId = new Guid("590cc0e4-8be8-48e8-97b8-908ea7a1fc9a"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("d8e8c71b-0234-4742-811a-71ad0e65a094"),
                            Amount = 14m,
                            Label = "Regular",
                            MenuItemId = new Guid("3b7745b6-66d4-4db7-8ee3-b018834f58f7"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("7a5b50d6-a069-41d1-af29-4d308a93e9da"),
                            Amount = 13m,
                            Label = "Regular",
                            MenuItemId = new Guid("1af4708e-e741-4621-95e3-6c8f24af2be6"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("d1d39b7a-30a0-4a9a-b9b0-c8dd1c8c4c74"),
                            Amount = 14m,
                            Label = "Regular",
                            MenuItemId = new Guid("e1fd2b7f-d7e0-47cc-9e3e-4bc3a30aa4b8"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("abaa4242-5fa4-463f-af31-83bbd4a97bea"),
                            Amount = 11m,
                            Label = "Regular",
                            MenuItemId = new Guid("7626d0df-9f8a-4fe8-9062-3596165e148a"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("a57aa41f-25a7-46a0-b346-2b557de1d9c1"),
                            Amount = 13m,
                            Label = "Regular",
                            MenuItemId = new Guid("ecfc8bfa-6c51-4607-b7ff-fe9f59db8fbc"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("724eb0d3-0208-43bc-9da4-eae38cb79f45"),
                            Amount = 14m,
                            Label = "Regular",
                            MenuItemId = new Guid("6e97a8ee-16b1-4feb-b6e0-2ab4e56658a0"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("3aee6764-1cf7-492e-b597-e0a511e17978"),
                            Amount = 14m,
                            Label = "Regular",
                            MenuItemId = new Guid("90dce7e3-9cc6-4732-b7d2-f4d43056fbb8"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("b6cc31de-9405-4ac0-b5e9-1505fbe9a83a"),
                            Amount = 13m,
                            Label = "Regular",
                            MenuItemId = new Guid("0d440a2b-06a3-47f9-b129-1544f2f391a8"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("d3f87dde-7690-4820-87a4-b065dd5b81d6"),
                            Amount = 13m,
                            Label = "Regular",
                            MenuItemId = new Guid("95f39c20-e1ba-4fd2-992d-8d9e19600d64"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("c3ed0da2-245d-44c1-854e-3428f91f2e2b"),
                            Amount = 13m,
                            Label = "Regular",
                            MenuItemId = new Guid("6f2a75a4-c1e2-458f-bde4-d825f987cc3d"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("1d14709d-c8b9-46b9-91cb-f997ac37bce0"),
                            Amount = 7m,
                            Label = "Regular",
                            MenuItemId = new Guid("b7ab3351-1b6b-45d0-b7b4-9782d79cfc65"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("d1a821d1-d919-45d4-a11d-13ede02f145d"),
                            Amount = 7m,
                            Label = "Regular",
                            MenuItemId = new Guid("5b1c6127-f7f0-497a-88b9-537e9110176f"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("40e09332-7d77-44fa-b03a-b24e9a65d1a5"),
                            Amount = 7m,
                            Label = "Regular",
                            MenuItemId = new Guid("06f858a2-f226-4b2f-a912-a6330bbf4ec1"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("cf5a1b06-f3ad-47f7-8c3f-d5d0b6823b24"),
                            Amount = 6m,
                            Label = "Regular",
                            MenuItemId = new Guid("8fcaa555-d618-4ad8-ae73-abf51854a329"),
                            SortOrder = 1
                        },
                        new
                        {
                            MenuItemPriceVariantId = new Guid("0dc7e9f1-2c5a-490a-8919-80d2983cd1e1"),
                            Amount = 6m,
                            Label = "Regular",
                            MenuItemId = new Guid("44472c07-5f31-482a-8506-8a3c11cf1f26"),
                            SortOrder = 1
                        });
                });

            modelBuilder.Entity("Anchor.Infrastructure.Data.Menu.MenuItemTabEntity", b =>
                {
                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tab")
                        .HasColumnType("int");

                    b.HasKey("MenuItemId", "Tab");

                    b.ToTable("MenuItemTabs", (string)null);

                    b.HasData(
                        new
                        {
                            MenuItemId = new Guid("c88652a0-c9f2-4a7d-b4ac-8ddbfc9ff4e5"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("c88652a0-c9f2-4a7d-b4ac-8ddbfc9ff4e5"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("5c3a9530-0f24-4d62-883b-f01b0a4286c2"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("5c3a9530-0f24-4d62-883b-f01b0a4286c2"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("ff4ee65c-89e7-49f7-9023-8579ccb8307b"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("ff4ee65c-89e7-49f7-9023-8579ccb8307b"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("e75d8a92-f1d2-4d58-9cd0-9b7e80ce9d80"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("e75d8a92-f1d2-4d58-9cd0-9b7e80ce9d80"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("79663ef8-29ff-4d24-8b1c-cfa8dad8ba72"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("79663ef8-29ff-4d24-8b1c-cfa8dad8ba72"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("1c4d4f34-5260-4f7d-abcb-1c6875b7ebf8"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("1c4d4f34-5260-4f7d-abcb-1c6875b7ebf8"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("ca5cd1b7-8c73-4b21-b3e4-8e98fea44ee9"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("ca5cd1b7-8c73-4b21-b3e4-8e98fea44ee9"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("73ea7283-893f-4d14-8081-39f63bd54d13"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("73ea7283-893f-4d14-8081-39f63bd54d13"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("8c5bde4d-3fb2-4a02-8ab5-40d3e0b49387"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("8c5bde4d-3fb2-4a02-8ab5-40d3e0b49387"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("e9d5a6c9-9a4c-4e98-8c72-2ae28bfcba97"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("e9d5a6c9-9a4c-4e98-8c72-2ae28bfcba97"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("db2a7b2f-d9e9-4433-80a3-baeb5e5b5728"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("db2a7b2f-d9e9-4433-80a3-baeb5e5b5728"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("590cc0e4-8be8-48e8-97b8-908ea7a1fc9a"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("590cc0e4-8be8-48e8-97b8-908ea7a1fc9a"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("3b7745b6-66d4-4db7-8ee3-b018834f58f7"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("3b7745b6-66d4-4db7-8ee3-b018834f58f7"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("1af4708e-e741-4621-95e3-6c8f24af2be6"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("1af4708e-e741-4621-95e3-6c8f24af2be6"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("e1fd2b7f-d7e0-47cc-9e3e-4bc3a30aa4b8"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("e1fd2b7f-d7e0-47cc-9e3e-4bc3a30aa4b8"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("7626d0df-9f8a-4fe8-9062-3596165e148a"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("7626d0df-9f8a-4fe8-9062-3596165e148a"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("ecfc8bfa-6c51-4607-b7ff-fe9f59db8fbc"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("ecfc8bfa-6c51-4607-b7ff-fe9f59db8fbc"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("6e97a8ee-16b1-4feb-b6e0-2ab4e56658a0"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("6e97a8ee-16b1-4feb-b6e0-2ab4e56658a0"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("90dce7e3-9cc6-4732-b7d2-f4d43056fbb8"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("90dce7e3-9cc6-4732-b7d2-f4d43056fbb8"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("0d440a2b-06a3-47f9-b129-1544f2f391a8"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("0d440a2b-06a3-47f9-b129-1544f2f391a8"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("95f39c20-e1ba-4fd2-992d-8d9e19600d64"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("95f39c20-e1ba-4fd2-992d-8d9e19600d64"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("6f2a75a4-c1e2-458f-bde4-d825f987cc3d"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("6f2a75a4-c1e2-458f-bde4-d825f987cc3d"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("b7ab3351-1b6b-45d0-b7b4-9782d79cfc65"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("b7ab3351-1b6b-45d0-b7b4-9782d79cfc65"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("5b1c6127-f7f0-497a-88b9-537e9110176f"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("5b1c6127-f7f0-497a-88b9-537e9110176f"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("06f858a2-f226-4b2f-a912-a6330bbf4ec1"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("06f858a2-f226-4b2f-a912-a6330bbf4ec1"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("8fcaa555-d618-4ad8-ae73-abf51854a329"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("8fcaa555-d618-4ad8-ae73-abf51854a329"),
                            Tab = 3
                        },
                        new
                        {
                            MenuItemId = new Guid("44472c07-5f31-482a-8506-8a3c11cf1f26"),
                            Tab = 2
                        },
                        new
                        {
                            MenuItemId = new Guid("44472c07-5f31-482a-8506-8a3c11cf1f26"),
                            Tab = 3
                        });
                });

            modelBuilder.Entity("Anchor.Infrastructure.Data.Menu.MenuSectionEntity", b =>
                {
                    b.Property<Guid>("MenuSectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Family")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisibleToGuests")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("MenuSectionId");

                    b.ToTable("MenuSections", (string)null);

                    b.HasData(
                        new
                        {
                            MenuSectionId = new Guid("0e4de526-5921-4c3b-8985-d83344642a41"),
                            Family = 1,
                            IsArchived = false,
                            IsVisibleToGuests = true,
                            Name = "Dinner Specials",
                            SortOrder = 0
                        },
                        new
                        {
                            MenuSectionId = new Guid("d67bd219-6d64-4a08-8ce4-d036a0c7b16d"),
                            Family = 1,
                            IsArchived = false,
                            IsVisibleToGuests = true,
                            Name = "Appetizers",
                            SortOrder = 1
                        },
                        new
                        {
                            MenuSectionId = new Guid("4a3a2d15-2af0-44a7-84c8-67b603a3ddb4"),
                            Family = 1,
                            IsArchived = false,
                            IsVisibleToGuests = true,
                            Name = "Wings",
                            SortOrder = 2
                        },
                        new
                        {
                            MenuSectionId = new Guid("31e9cb99-5fca-4a4a-a04b-89b97c926a52"),
                            Family = 1,
                            IsArchived = false,
                            IsVisibleToGuests = true,
                            Name = "Soups & Salads",
                            SortOrder = 3
                        },
                        new
                        {
                            MenuSectionId = new Guid("7f644c28-9275-4df8-8e4b-482f47568cfb"),
                            Family = 1,
                            IsArchived = false,
                            IsVisibleToGuests = true,
                            Name = "Sandwiches",
                            SortOrder = 4
                        },
                        new
                        {
                            MenuSectionId = new Guid("198ccf8a-72fd-4278-a360-f36d5871e58b"),
                            Family = 1,
                            IsArchived = false,
                            IsVisibleToGuests = true,
                            Name = "Burgers",
                            SortOrder = 5
                        },
                        new
                        {
                            MenuSectionId = new Guid("fa5da0f9-7e81-4b9d-9e11-fa5b1f828c72"),
                            Family = 1,
                            IsArchived = false,
                            IsVisibleToGuests = true,
                            Name = "Wraps",
                            SortOrder = 6
                        },
                        new
                        {
                            MenuSectionId = new Guid("2ea5e671-e8ac-4c8a-b3d9-4c136a32a71b"),
                            Family = 1,
                            IsArchived = false,
                            IsVisibleToGuests = true,
                            Name = "Kids Menu",
                            SortOrder = 7
                        },
                        new
                        {
                            MenuSectionId = new Guid("a8f0b603-e02d-49f5-873d-1bb6bfc16c0f"),
                            Family = 1,
                            IsArchived = false,
                            IsVisibleToGuests = true,
                            Name = "Desserts",
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("Anchor.Infrastructure.Data.Menu.MenuServiceWindowEntity", b =>
                {
                    b.Property<int>("Tab")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("ClosesAt")
                        .HasColumnType("time");

                    b.Property<bool>("ClosesNextDay")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<TimeOnly?>("OpensAt")
                        .HasColumnType("time");

                    b.HasKey("Tab", "DayOfWeek");

                    b.ToTable("MenuServiceWindows", (string)null);

                    b.HasData(
                        new
                        {
                            Tab = 1,
                            DayOfWeek = 1,
                            ClosesNextDay = false,
                            IsAvailable = false
                        },
                        new
                        {
                            Tab = 1,
                            DayOfWeek = 2,
                            ClosesNextDay = false,
                            IsAvailable = false
                        },
                        new
                        {
                            Tab = 1,
                            DayOfWeek = 3,
                            ClosesNextDay = false,
                            IsAvailable = false
                        },
                        new
                        {
                            Tab = 1,
                            DayOfWeek = 4,
                            ClosesNextDay = false,
                            IsAvailable = false
                        },
                        new
                        {
                            Tab = 1,
                            DayOfWeek = 5,
                            ClosesNextDay = false,
                            IsAvailable = false
                        },
                        new
                        {
                            Tab = 1,
                            DayOfWeek = 6,
                            ClosesAt = new TimeOnly(13, 0, 0),
                            ClosesNextDay = false,
                            IsAvailable = true,
                            OpensAt = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Tab = 1,
                            DayOfWeek = 0,
                            ClosesAt = new TimeOnly(13, 0, 0),
                            ClosesNextDay = false,
                            IsAvailable = true,
                            OpensAt = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Tab = 2,
                            DayOfWeek = 1,
                            ClosesNextDay = false,
                            IsAvailable = false
                        },
                        new
                        {
                            Tab = 2,
                            DayOfWeek = 2,
                            ClosesAt = new TimeOnly(16, 0, 0),
                            ClosesNextDay = false,
                            IsAvailable = true,
                            OpensAt = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Tab = 2,
                            DayOfWeek = 3,
                            ClosesAt = new TimeOnly(16, 0, 0),
                            ClosesNextDay = false,
                            IsAvailable = true,
                            OpensAt = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Tab = 2,
                            DayOfWeek = 4,
                            ClosesAt = new TimeOnly(16, 0, 0),
                            ClosesNextDay = false,
                            IsAvailable = true,
                            OpensAt = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Tab = 2,
                            DayOfWeek = 5,
                            ClosesAt = new TimeOnly(16, 0, 0),
                            ClosesNextDay = false,
                            IsAvailable = true,
                            OpensAt = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Tab = 2,
                            DayOfWeek = 6,
                            ClosesAt = new TimeOnly(16, 0, 0),
                            ClosesNextDay = false,
                            IsAvailable = true,
                            OpensAt = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Tab = 2,
                            DayOfWeek = 0,
                            ClosesAt = new TimeOnly(15, 0, 0),
                            ClosesNextDay = false,
                            IsAvailable = true,
                            OpensAt = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Tab = 3,
                            DayOfWeek = 1,
                            ClosesAt = new TimeOnly(20, 0, 0),
                            ClosesNextDay = false,
                            IsAvailable = true,
                            OpensAt = new TimeOnly(17, 0, 0)
                        },
                        new
                        {
                            Tab = 3,
                            DayOfWeek = 2,
                            ClosesAt = new TimeOnly(21, 0, 0),
                            ClosesNextDay = false,
                            IsAvailable = true,
                            OpensAt = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            Tab = 3,
                            DayOfWeek = 3,
                            ClosesAt = new TimeOnly(21, 0, 0),
                            ClosesNextDay = false,
                            IsAvailable = true,
                            OpensAt = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            Tab = 3,
                            DayOfWeek = 4,
                            ClosesAt = new TimeOnly(21, 0, 0),
                            ClosesNextDay = false,
                            IsAvailable = true,
                            OpensAt = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            Tab = 3,
                            DayOfWeek = 5,
                            ClosesAt = new TimeOnly(22, 0, 0),
                            ClosesNextDay = false,
                            IsAvailable = true,
                            OpensAt = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            Tab = 3,
                            DayOfWeek = 6,
                            ClosesAt = new TimeOnly(22, 0, 0),
                            ClosesNextDay = false,
                            IsAvailable = true,
                            OpensAt = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            Tab = 3,
                            DayOfWeek = 0,
                            ClosesAt = new TimeOnly(20, 0, 0),
                            ClosesNextDay = false,
                            IsAvailable = true,
                            OpensAt = new TimeOnly(15, 0, 0)
                        },
                        new
                        {
                            Tab = 4,
                            DayOfWeek = 1,
                            ClosesAt = new TimeOnly(21, 0, 0),
                            ClosesNextDay = false,
                            IsAvailable = true,
                            OpensAt = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            Tab = 4,
                            DayOfWeek = 2,
                            ClosesAt = new TimeOnly(22, 0, 0),
                            ClosesNextDay = false,
                            IsAvailable = true,
                            OpensAt = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Tab = 4,
                            DayOfWeek = 3,
                            ClosesAt = new TimeOnly(22, 0, 0),
                            ClosesNextDay = false,
                            IsAvailable = true,
                            OpensAt = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Tab = 4,
                            DayOfWeek = 4,
                            ClosesAt = new TimeOnly(22, 0, 0),
                            ClosesNextDay = false,
                            IsAvailable = true,
                            OpensAt = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Tab = 4,
                            DayOfWeek = 5,
                            ClosesAt = new TimeOnly(0, 0, 0),
                            ClosesNextDay = true,
                            IsAvailable = true,
                            OpensAt = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Tab = 4,
                            DayOfWeek = 6,
                            ClosesAt = new TimeOnly(0, 0, 0),
                            ClosesNextDay = true,
                            IsAvailable = true,
                            OpensAt = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Tab = 4,
                            DayOfWeek = 0,
                            ClosesAt = new TimeOnly(21, 0, 0),
                            ClosesNextDay = false,
                            IsAvailable = true,
                            OpensAt = new TimeOnly(10, 0, 0)
                        });
                });

            modelBuilder.Entity("Anchor.Infrastructure.Data.Menu.RecurringSpecialEntity", b =>
                {
                    b.Property<Guid>("RecurringSpecialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisibleToGuests")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LinkedMenuItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MenuSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PriceNote")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Tab")
                        .HasColumnType("int");

                    b.Property<string>("TimeNote")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("RecurringSpecialId");

                    b.HasIndex("LinkedMenuItemId");

                    b.HasIndex("MenuSectionId");

                    b.ToTable("RecurringSpecials", (string)null);

                    b.HasData(
                        new
                        {
                            RecurringSpecialId = new Guid("33d64e7b-d5b7-481a-97fc-7f250a68c27e"),
                            DayOfWeek = 1,
                            Description = "A dependable burger-night draw with fries and easy weeknight pricing.",
                            IsArchived = false,
                            IsVisibleToGuests = true,
                            LinkedMenuItemId = new Guid("7626d0df-9f8a-4fe8-9062-3596165e148a"),
                            MenuSectionId = new Guid("198ccf8a-72fd-4278-a360-f36d5871e58b"),
                            PriceNote = "$11 basket special",
                            SortOrder = 1,
                            Tab = 3,
                            TimeNote = "After 5:00 PM",
                            Title = "Monday Night Burgers"
                        },
                        new
                        {
                            RecurringSpecialId = new Guid("5ee7bbea-c2f4-4d5b-bcdb-bd0fd0a06704"),
                            DayOfWeek = 2,
                            Description = "A taco-night feature built for quick dinner traffic and casual bar seating.",
                            IsArchived = false,
                            IsVisibleToGuests = true,
                            LinkedMenuItemId = new Guid("e75d8a92-f1d2-4d58-9cd0-9b7e80ce9d80"),
                            MenuSectionId = new Guid("d67bd219-6d64-4a08-8ce4-d036a0c7b16d"),
                            PriceNote = "$10 dinner feature",
                            SortOrder = 2,
                            Tab = 3,
                            TimeNote = "After 4:00 PM",
                            Title = "Tuesday Taco Basket"
                        },
                        new
                        {
                            RecurringSpecialId = new Guid("7e8222c3-63ec-4b4b-b777-d1e3aa7c5a86"),
                            DayOfWeek = 3,
                            Description = "Sauced wings with a strong shareable hook for midweek regulars.",
                            IsArchived = false,
                            IsVisibleToGuests = true,
                            LinkedMenuItemId = new Guid("1c4d4f34-5260-4f7d-abcb-1c6875b7ebf8"),
                            MenuSectionId = new Guid("4a3a2d15-2af0-44a7-84c8-67b603a3ddb4"),
                            PriceNote = "$16 dozen special",
                            SortOrder = 3,
                            Tab = 3,
                            TimeNote = "After 5:00 PM",
                            Title = "Wing Night"
                        },
                        new
                        {
                            RecurringSpecialId = new Guid("88bb945a-b7b4-4725-972b-60a042e524e9"),
                            DayOfWeek = 5,
                            Description = "A Friday dinner anchor that deserves a permanent home in the guest menu flow.",
                            IsArchived = false,
                            IsVisibleToGuests = true,
                            LinkedMenuItemId = new Guid("e1fd2b7f-d7e0-47cc-9e3e-4bc3a30aa4b8"),
                            MenuSectionId = new Guid("7f644c28-9275-4df8-8e4b-482f47568cfb"),
                            PriceNote = "$15 dinner plate",
                            SortOrder = 4,
                            Tab = 3,
                            TimeNote = "After 4:00 PM",
                            Title = "Friday Fish Fry"
                        },
                        new
                        {
                            RecurringSpecialId = new Guid("6baa63b3-55c9-4e47-8555-803573b9b38d"),
                            DayOfWeek = 0,
                            Description = "A hearty end-of-week dinner special that should read as a repeatable tradition.",
                            IsArchived = false,
                            IsVisibleToGuests = true,
                            MenuSectionId = new Guid("0e4de526-5921-4c3b-8985-d83344642a41"),
                            PriceNote = "$17 dinner plate",
                            SortOrder = 5,
                            Tab = 3,
                            TimeNote = "After 3:00 PM",
                            Title = "Sunday Pork Chop Dinner"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("varbinary(1024)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserPasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Anchor.Infrastructure.Data.Menu.MenuItemEntity", b =>
                {
                    b.HasOne("Anchor.Infrastructure.Data.Menu.MenuSectionEntity", "Section")
                        .WithMany("Items")
                        .HasForeignKey("MenuSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Anchor.Infrastructure.Data.Menu.MenuItemPriceVariantEntity", b =>
                {
                    b.HasOne("Anchor.Infrastructure.Data.Menu.MenuItemEntity", "Item")
                        .WithMany("PriceVariants")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Anchor.Infrastructure.Data.Menu.MenuItemTabEntity", b =>
                {
                    b.HasOne("Anchor.Infrastructure.Data.Menu.MenuItemEntity", "Item")
                        .WithMany("FoodTabs")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Anchor.Infrastructure.Data.Menu.RecurringSpecialEntity", b =>
                {
                    b.HasOne("Anchor.Infrastructure.Data.Menu.MenuItemEntity", "LinkedMenuItem")
                        .WithMany("LinkedRecurringSpecials")
                        .HasForeignKey("LinkedMenuItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Anchor.Infrastructure.Data.Menu.MenuSectionEntity", "Section")
                        .WithMany("RecurringSpecials")
                        .HasForeignKey("MenuSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LinkedMenuItem");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Anchor.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Anchor.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.HasOne("Anchor.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<long>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("AspNetUserPasskeys");

                            b1
                                .ToJson("Data")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Anchor.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Anchor.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Anchor.Infrastructure.Data.Menu.MenuItemEntity", b =>
                {
                    b.Navigation("FoodTabs");

                    b.Navigation("LinkedRecurringSpecials");

                    b.Navigation("PriceVariants");
                });

            modelBuilder.Entity("Anchor.Infrastructure.Data.Menu.MenuSectionEntity", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("RecurringSpecials");
                });
#pragma warning restore 612, 618
        }
    }
}
